### ISSUE TITLE
等待watermark_image_exculed_plugin实现

### ISSUE THREAD

**Issue by Nenot233** [X-Skirt-X/nonebot-plugin-watermarker#3]
由于GIF也会出现水印，导致无法正常发送GIF

**Comment by PackageInstaller** [comment]
刚想提issues你这就发了哈哈

**Comment by ChenXu233** [comment]
> 由于GIF也会出现水印，导致无法正常发送GIF

到时候为GIF也添加一个适配,然后新增配置针对不同类型的图片选择性加水印(((

**Comment by ChenXu233** [comment]
真糟糕,因为不能在on_calling_api钩子函数里面获取调用api的插件信息(ddl:调用api行为和插件无关),所以这个插件目前只能无差别攻击
总之我还是先把GIF适配整了

**Comment by ChenXu233** [comment]
![40BG{C_%(RWIXP~LB4AXR2](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/cd970313-b61c-44b9-99e7-3c40f902b6df)
再咕一个星期,获得调用API的插件信息的方法已经知道了(current_matcher),完工在望

base64padding的问题解决了(

**Comment by Nenot233** [comment]
![](https://user-images.githubusercontent.com/91937041/241466839-cd970313-b61c-44b9-99e7-3c40f902b6df.gif)

**Comment by PackageInstaller** [comment]
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/285183a9-f0c9-499e-bbca-90078a978497)

**Comment by PackageInstaller** [comment]
话说能对特定插件排除水印吗，我超分图片，出来的图带水印，就很怪（（（（

**Comment by ChenXu233** [comment]
> 话说能对特定插件排除水印吗，我超分图片，出来的图带水印，就很怪（（（（

### 在写了在写了
(可以用的版本已经传上GitHub了,但是pip的版本还没有上传,准备和GIF适配一起做了在弄到pip上)
![E$K2)SY{{ R33 OVDCJM(~D](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/a851ce00-55f4-402c-a121-6d422b8c2970)

**Comment by ChenXu233** [comment]
# 完成了!

![_2V7KI@M`0SD83 `BXE7IES](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/b9e1d1ce-1a21-4b64-b96c-dc532d49cdf3)

**Comment by PackageInstaller** [comment]
好，让我git pull

**Comment by PackageInstaller** [comment]
watermark_image_exculed_plugin = [extensive_plugin.plugins.super_resolution]这样设置了还是不行

**Comment by ChenXu233** [comment]
> watermark_image_exculed_plugin = [extensive_plugin.plugins.super_resolution]这样设置了还是不行

给插件名称加双引号,这个里面其实是一个列表里面用字符串代表插件名称
如:
```
watermark_image_exculed_plugin = ["extensive_plugin.plugins.super_resolution","其他插件名称"]
```

**Comment by PackageInstaller** [comment]
> > watermark_image_exculed_plugin = [extensive_plugin.plugins.super_resolution]这样设置了还是不行
> 
> 给插件名称加双引号,这个里面其实是一个列表里面用字符串代表插件名称 如:
> 
> ```
> watermark_image_exculed_plugin = ["extensive_plugin.plugins.super_resolution","其他插件名称"]
> ```

还是不行，我看看真寻手册先

**Comment by ChenXu233** [comment]
> > > watermark_image_exculed_plugin = [extensive_plugin.plugins.super_resolution]这样设置了还是不行
> > 
> > 
> > 给插件名称加双引号,这个里面其实是一个列表里面用字符串代表插件名称 如:
> > ```
> > watermark_image_exculed_plugin = ["extensive_plugin.plugins.super_resolution","其他插件名称"]
> > ```
> 
> 还是不行，我看看真寻手册先

那我找个机会弄个真寻bot在本地试试(

**Comment by PackageInstaller** [comment]
> 草,那我找个机会把真寻bot弄下来试试

速速做个真寻适配版（（（

**Comment by ChenXu233** [comment]
![)Y1G~_ }8@0I)71` }I0M0K_tmb](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/2212e11e-7c86-4c52-be4e-69abcb475ee6)

**Comment by ChenXu233** [comment]
> > 草,那我找个机会把真寻bot弄下来试试
> 
> 速速做个真寻适配版（（（

草,不想搭建数据库,你能不能给我看看你的真寻运行的debug日志什么的,我看看每个matcher名称是什么,这样好有针对性的修改
![_L}@SARWO%%G)YYP(6@F(RH](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/20292292-8d4e-4844-b95b-f483022d55ac)

**Comment by PackageInstaller** [comment]
> > > 草,那我找个机会把真寻bot弄下来试试
> > 
> > 速速做个真寻适配版（（（
> 
> 草,不想搭建数据库,你能不能给我看看你的真寻运行的debug日志什么的,我看看每个matcher名称是什么,这样好有针对性的修改
> ![_L}@SARWO%%G)YYP(6@F(RH](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/20292292-8d4e-4844-b95b-f483022d55ac)
> 

不知道为什么，我在.env.dev中设置DEBUG=True后后台还是正常的样子

**Comment by PackageInstaller** [comment]
唯一一次卡出来debu模式还是在装了拟声鸟那个插件的依赖后，但是我现在是python3.11，那个依赖要3.10

**Comment by ChenXu233** [comment]
要不问问真寻bot群的群友们((

**Comment by ChenXu233** [comment]
其实INFO也可以((
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/e6f84e79-3538-40dc-a072-db281bc7e793)

可以在INFO中看见
```
06-03 22:37:33 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_petpet) running complete
```
内有Matcher的一些信息,这个Matcher有跟随着插件的名字
```
module=extensive_plugin.nonebot_plugin_petpet
```
在配置项内填入
```
watermark_image_exculed_plugin = ["extensive_plugin.super_resolution","其他插件名称"]
```
即可成功((

------------------------------------------

接下来出什么大事估计得明天搞了**

**Comment by PackageInstaller** [comment]
> 其实INFO也可以(( ![image](https://user-images.githubusercontent.com/91937041/243103829-e6f84e79-3538-40dc-a072-db281bc7e793.png)
> 
> 可以在INFO中看见
> 
> ```
> 06-03 22:37:33 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_petpet) running complete
> ```
> 
> 内有Matcher的一些信息,这个Matcher有跟随着插件的名字
> 
> ```
> module=extensive_plugin.nonebot_plugin_petpet
> ```
> 
> 在配置项内填入
> 
> ```
> watermark_image_exculed_plugin = ["extensive_plugin.super_resolution","其他插件名称"]
> ```
> 
> 即可成功((
> 
> 接下来出什么大事估计得明天搞了**

大概就是这样吧ba
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/00c2e7a3-c2f6-4188-b0da-7763980aaaab)
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/b61cc330-057b-4271-855f-3c7838874b59)
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/21215981-1996-4f8c-8f94-822307bbe967)

**Comment by PackageInstaller** [comment]
虽然有报错，但是带上了水印（）

**Comment by ChenXu233** [comment]
奇怪了,要不你直接改插件里的config.py?
https://github.com/X-Skirt-X/nonebot-plugin-watermarker/blob/2376bf417abc8ce0bd2ce477b48b333183ba611c/nonebot_plugin_watermarker/config.py#L16
往这里加(?

**Comment by ChenXu233** [comment]
实在不行我写个logINFO输出插件名称
然后根据这个插件名称去改

**Comment by PackageInstaller** [comment]
> 奇怪了,要不你直接改插件里的config.py?
> https://github.com/X-Skirt-X/nonebot-plugin-watermarker/blob/2376bf417abc8ce0bd2ce477b48b333183ba611c/nonebot_plugin_watermarker/config.py#L16
> 往这里加(?


 你怎么知道我们真寻Bot玩家一般都是直接改config.py的（bushi，在加了，重启中
![18a9cba92c39a317.gif](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/c8477888-fe97-4d8a-9587-bc90dd433498)

**Comment by PackageInstaller** [comment]
加了后还是不行
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/06a72ce4-b431-4682-b4f1-c2233ad51d31)

后台截图
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/b0b414cf-4b81-4b26-b009-86b3c755a0da)
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/4c17bd5c-f9af-4ee6-b0fc-a45d132178d3)

**Comment by ChenXu233** [comment]
试试GitHub版本,然后再看日志(等我push上来((
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/91937041/7c536935-dad8-4a5e-a01d-46281ca022bf)

**Comment by ChenXu233** [comment]
现在再看看(?

**Comment by PackageInstaller** [comment]
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/162f1a88-6c00-4929-9a83-884a756d389e)

**Comment by ChenXu233** [comment]
> ![image](https://user-images.githubusercontent.com/80018096/243107912-162f1a88-6c00-4929-9a83-884a756d389e.png)

看看你的config.py(感觉应该没问题啊*

**Comment by PackageInstaller** [comment]
![image](https://github.com/X-Skirt-X/nonebot-plugin-watermarker/assets/80018096/9c13be91-8e48-4a2e-94d2-4eaffd5de11a)

**Comment by ChenXu233** [comment]
感觉没问题啊,诡异啊,我自己这里都能用的

**Comment by ChenXu233** [comment]
> ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)

看起来有点像中文逗号

**Comment by PackageInstaller** [comment]
> > ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)
> 
> 看起来有点像中文逗号
> 

不可能，我这用英文引号自动补全的，要是中文直接报错

**Comment by ChenXu233** [comment]
> > > ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)
> > 
> > 看起来有点像中文逗号
> > 
> 
> 不可能，我这用英文引号自动补全的，要是中文直接报错

问题解决了吗？没有解决的话咱QQ上继续吧，这里不太好搞，你可以把QQ号发到我邮箱()

**Comment by PackageInstaller** [comment]
> > > > ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)
> > > 
> > > 
> > > 看起来有点像中文逗号
> > 
> > 
> > 不可能，我这用英文引号自动补全的，要是中文直接报错
> 
> 问题解决了吗？没有解决的话咱QQ上继续吧，这里不太好搞，你可以把QQ号发到我邮箱()

我不知道你邮箱啊

**Comment by ChenXu233** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)
> > > > 
> > > > 
> > > > 看起来有点像中文逗号
> > > 
> > > 
> > > 不可能，我这用英文引号自动补全的，要是中文直接报错
> > 
> > 问题解决了吗？没有解决的话咱QQ上继续吧，这里不太好搞，你可以把QQ号发到我邮箱()
> 
> 我不知道你邮箱啊

GitHub上有啊()
Woyerpa@outlook.com

**Comment by PackageInstaller** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/80018096/243146497-9c13be91-8e48-4a2e-94d2-4eaffd5de11a.png)
> > > > > 
> > > > > 
> > > > > 看起来有点像中文逗号
> > > > 
> > > > 
> > > > 不可能，我这用英文引号自动补全的，要是中文直接报错
> > > 
> > > 
> > > 问题解决了吗？没有解决的话咱QQ上继续吧，这里不太好搞，你可以把QQ号发到我邮箱()
> > 
> > 
> > 我不知道你邮箱啊
> 
> GitHub上有啊() [Woyerpa@outlook.com](mailto:Woyerpa@outlook.com)

发你了

**Comment by ChenXu233** [comment]
理论上这个问题已经被解决，关issue咯。
